Repository Flint-org/Flint-Front, pull requests merged in 2023-08, with the labels that each got.

#9 Feat/#6 email verification page
  assets/images/alert.svg
  components/common/OrangeNextBtn.jsx
  components/signup/CertificatePage.jsx
  components/signup/EmailVerificationPage.jsx
  components/signup/EmailVerificationPage2.jsx
  components/signup/SignupHeader.jsx
  screens/Signup.js
Labels: Feat

#7 Feat/#5 sns login
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
  components/KakaoLoginTest.js
  components/NaverLoginTest.js
  ios/Podfile.lock
  ios/flintfront.xcodeproj/project.pbxproj
  ios/flintfront.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/flintfront/AppDelegate.mm
  ios/flintfront/Info.plist
  package-lock.json
  package.json
Labels: Feat

#11 Feat/#10 start page
  assets/images/flint_logo.svg
  assets/images/kakao_logo.svg
  assets/images/naver_logo.svg
  components/signup/StartPage.jsx
Labels: Feat

#21 Feat/#20 sns link
  components/KakaoLoginTest.js
  components/NaverLoginTest.js
  components/signup/StartPage.jsx
  ios/Podfile.lock
Labels: Feat

#23 Feat/#22 page flow change
  components/signup/CertificatePage.jsx
  components/signup/DetailsInfoPage.jsx
  components/signup/EmailVerificationPage.jsx
  components/signup/EmailVerificationPage2.jsx
  components/signup/SignupHeader.jsx
Labels: Feat

#25 Feat/Splash Screeen 적용 및 아이콘 변경
  App.js
  app.json
  ios/flintfront/Images.xcassets/SplashScreen.imageset/image.png
Labels: Feat

#26 Feat/#24 card component
  assets/images/logo_symbol_white.svg
  assets/images/plus.svg
  package-lock.json
  package.json
  screens/BottomTabs/Card/CardComponent.jsx
  screens/BottomTabs/Card/MyCard.jsx
Labels: Feat

#27 Feat/#2 join page
  App.js
  App.jsx
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
  app.json
  assets/images/alert.svg
  assets/images/arrow_down.svg
  assets/images/arrow_up.svg
  assets/images/back_arrow.svg
  assets/images/camera.svg
  assets/images/check.svg
  assets/images/close.svg
  assets/images/flint_logo.svg
  assets/images/kakao_logo.svg
  assets/images/naver_logo.svg
  assets/images/search.svg
  ios/Podfile.lock
  ios/flintfront.xcodeproj/project.pbxproj
  ios/flintfront.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/flintfront/AppDelegate.mm
  ios/flintfront/Images.xcassets/SplashScreen.imageset/image.png
  ios/flintfront/Info.plist
  navigation/Root.jsx
  navigation/Stack.jsx
  package-lock.json
  package.json
  screens/common/AlertModal.jsx
  screens/common/OrangeNextBtn.jsx
  screens/signup/Signup.jsx
  screens/signup/pages/CertificatePage.jsx
  screens/signup/pages/DetailsInfoPage.jsx
  screens/signup/pages/EmailVerificationPage.jsx
  screens/signup/pages/EmailVerificationPage2.jsx
  screens/signup/pages/InfoDropdown.jsx
  screens/signup/pages/SignupHeader.jsx
  screens/signup/pages/StartPage.jsx
Labels: Feat

#30 Feat/#28 card component props
  components/bottomTabs/card/CardComponent.jsx
  screens/BottomTabs/Card/MyCard.jsx
Labels: Feat

#31 Feat/#29 mycard page
  assets/images/edit.svg
  navigation/Root.jsx
  screens/BottomTabs/Card/EditCard.jsx
  screens/BottomTabs/Card/MyCard.jsx
Labels: Feat

#33 Feat/#32 edit card page
  components/bottomTabs/card/CardComponent.jsx
  components/common/AlertModal.jsx
  navigation/BottomTabs.jsx
  screens/BottomTabs/Card.jsx
  screens/BottomTabs/Card/EditCard.jsx
  screens/BottomTabs/Card/MyCard.jsx
Labels: Feat

#38 dropdown 메뉴 검색 후 일치하는 사항 없을 시 문구 수정
  screens/signup/pages/InfoDropdown.jsx
Labels: Fix

#37 Chore/카카오 로그인 테스트 앱 키로 변경
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  ios/flintfront/Info.plist
  screens/signup/pages/StartPage.jsx
Labels: Chore

#39 Feat/#34 card box anim
  components/bottomTabs/card/BoxCardComponent.jsx
  ios/Podfile.lock
  navigation/Root.jsx
  navigation/Stack.jsx
  screens/BottomTabs/Card/CardBox.jsx
  screens/BottomTabs/Card/MyCard.jsx
  screens/signup/pages/DetailsInfoPage.jsx
Labels: Feat

#41 Feat/#40 redux import
  App.jsx
  index.js
  main.jsx
  package-lock.json
  package.json
  redux_modules/slice/userSlice.js
  redux_modules/store.js
  screens/signup/pages/StartPage.jsx
Labels: Chore, Feat

#47 Feat/#44 community navigation
  components/bottomTabs/home/board/BoardHeader.jsx
  components/bottomTabs/home/board/MajorSubHeader.jsx
  navigation/Stack.jsx
  package-lock.json
  screens/BottomTabs/Home.jsx
  screens/BottomTabs/home/GeneralBoard.jsx
  screens/BottomTabs/home/MajorBoard.jsx
  screens/BottomTabs/home/generalBoard/DateBoard.jsx
  screens/BottomTabs/home/generalBoard/FreeBoard.jsx
  screens/BottomTabs/home/generalBoard/FreshmanBoard.jsx
  screens/BottomTabs/home/generalBoard/PopularBoard.jsx
  screens/BottomTabs/home/generalBoard/PromotionBoard.jsx
  screens/BottomTabs/home/majorBoard/ArtsAthletics.jsx
  screens/BottomTabs/home/majorBoard/Education.jsx
  screens/BottomTabs/home/majorBoard/Engineering.jsx
  screens/BottomTabs/home/majorBoard/LiberalArts.jsx
  screens/BottomTabs/home/majorBoard/Medical.jsx
  screens/BottomTabs/home/majorBoard/NaturalScience.jsx
  screens/BottomTabs/home/majorBoard/Social.jsx
Labels: Feat
